//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPSM_Z2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bag
    {
        public int ID { get; set; }
        public Nullable<int> ID_Item { get; set; }
    
        public virtual Items Items { get; set; }
    }
}
