//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPSM_Z2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int ID { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> ID_Item { get; set; }
        public Nullable<double> Summa { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> ID_Client { get; set; }
        public Nullable<int> ID_Admin { get; set; }
    
        public virtual Admins Admins { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Items Items { get; set; }
    }
}
